import "./globals.css";
import {JetBrains_Mono} from "next/font/google";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

/*const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});*/

const jetBrainsMono = JetBrains_Mono({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
    variable: "--font-jetbrains-mono",
})

export const metadata = {
    title: "Ibradi-Dev", description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="fr">
        <body className={jetBrainsMono.variable}>
        <Header/>
        <StairTransition/>
        <PageTransition> {children} </PageTransition>
        </body>
        </html>);
}
